/*
 * File: app/view/incrementButton.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.incrementButton', {
    extend: 'Ext.Button',
    alias: 'widget.incrementButton',

    config: {
        itemId: 'mybutton',
        text: 5,
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap'
            }
        ]
    },

    onMybuttonTap: function(button, e, options) {
        var increment = button.getText();
        var start = Ext.getCmp('startButton');

        var startInt = start.getText();

        var total = parseInt(startInt, 10) + parseInt(increment, 10);

        start.setText(total);

        if(start.isHidden()) {
            start.show();
        }
    }

});