/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TimeCop3.view.Main', {
    extend: 'Ext.Container',
    requires: [
        'TimeCop3.view.incrementButton'
    ],

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'container',
                layout: {
                    type: 'hbox'
                },
                flex: 1,
                items: [
                    {
                        xtype: 'container',
                        width: 120,
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'incrementButton'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 1
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'fit'
                        },
                        width: 120,
                        items: [
                            {
                                xtype: 'incrementButton',
                                text: 10
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'hbox'
                },
                flex: 1,
                items: [
                    {
                        xtype: 'container',
                        flex: 1
                    },
                    {
                        xtype: 'container',
                        width: '',
                        layout: {
                            type: 'fit'
                        },
                        width: 120,
                        items: [
                            {
                                xtype: 'button',
                                hidden: true,
                                id: 'startButton',
                                itemId: 'mybutton5',
                                ui: 'roundStart',
                                text: 0
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 1
                    }
                ]
            },
            {
                xtype: 'container',
                layout: {
                    type: 'hbox'
                },
                flex: 1,
                items: [
                    {
                        xtype: 'container',
                        layout: {
                            type: 'fit'
                        },
                        width: 120,
                        items: [
                            {
                                xtype: 'incrementButton',
                                text: 30
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 1
                    },
                    {
                        xtype: 'container',
                        layout: {
                            type: 'fit'
                        },
                        width: 120,
                        items: [
                            {
                                xtype: 'incrementButton',
                                text: 60
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onStartButtonTap',
                event: 'tap',
                delegate: '#startButton'
            }
        ]
    },

    onStartButtonTap: function(button, e, options) {
        var delay = button.getText();
        setTimeout(function() {
            Ext.device.Notification.vibrate();
            Ext.device.Notification.show({
                title: 'Holy Crap!',
                message: 'Back to work minion! The boss needs a new villa!',
                callback: function(button) {
                    /* Do nothing */
                }
            });


        },parseInt(delay, 10)*1000);
    }

});